/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EnhancedPreviewDialog: typeof import('./src/components/EnhancedPreviewDialog.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FileThumbnail: typeof import('./src/components/FileThumbnail.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    NginxConfigManager: typeof import('./src/components/NginxConfigManager.vue')['default']
    QuickPreview: typeof import('./src/components/QuickPreview.vue')['default']
    ResponsiveDebugger: typeof import('./src/components/ResponsiveDebugger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
